# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napkin', '0003_auto_20160526_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='home_url',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
