# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napkin', '0004_auto_20160629_0522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='home_url',
        ),
        migrations.AddField(
            model_name='post',
            name='site_name',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AddField(
            model_name='post',
            name='site_url',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
