# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('napkin', '0002_auto_20160515_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group_id',
            new_name='group',
        ),
    ]
