# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('napkin', '0005_auto_20160629_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
